apiVersion: v1
kind: Service
metadata:
  name: logging-service
  namespace: api-gateway
spec:
  ports:
    - port: 4004
  selector:
    app: logging-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
  namespace: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      containers:
        - name: logging
          image: apigateway-logging-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4004
          envFrom:
            - configMapRef:
                name: gateway-config
          livenessProbe:
            httpGet:
              path: /health
              port: 4004
            initialDelaySeconds: 10
            periodSeconds: 10
